### PR TITLE
feat: Add several missing headers

### PR DESCRIPTION
**Pull request by icorderi**
- Re-export **SERVER** from `hyper::header::Server` as `ssdp::header::Server`
- Re-export **LOCATION** `hyper::header::Location` as `ssdp::header::Location`
- Re-export **CACHE-CONTROL** `hyper::header::CacheControl` as `ssdp::header::CacheControl`
- Re-export `hyper::header::CacheDirective` as `ssdp::header::CacheDirective`

### CODE REVIEW

**Comment by GGist** [comment]
Actually these headers are already in ```hyper``` http://hyper.rs/hyper/v0.9.3/hyper/header/index.html and users of our library can use any of the headers mentioned on that page with our messages.

However, if you wanted to re-export those headers from ```hyper``` in ```ssdp``` so that users dont have to import ```hyper``` in order to use them, that would probably be ok since those headers are commonly set in SSDP messages.

**Comment by icorderi** [comment]
@GGist, I got rid of the explicit unsafe impl Sync, and Send for the headers. 
Types are automatically Send and Sync unless something in them is !Send or !Sync.

**Comment by GGist** [comment]
Yeah I am not sure why I had those in there. This was one of the first crates I published so I think I misunderstood the auto derivation of ```Send``` and ```Sync``` back then.

On a side note, I wish the Rust developers made types ```#[derive()]``` those traits (or at least show it in the documentation) as I have found that for types that wrap things like ```UnsafeCell```, there is no way to tell that they aren't ```Sync``` without trying to compile.

Anyways, these changes look good. I see that some of the changes from the other pull request are in this one. If those aren't necessary for the code in this pull request (in particular, ```feat: Add several missing headers```) then you can remove those and I can merge this in now. You could then go back and rebase the other pull request as I left a comment on the other pull request that affects one of the commits.

**Comment by icorderi** [comment]
@ggist, ok I rebased it on **master** instead of being on top of the **feature/ipv6** branch. 
I also moved the _rustfmt.toml_ to this PR and added my IDE artifacts to the _.gitignore_. 

> Feel free to tweak the _rustfmt.toml_ line size to your liking, the default 80chars is a bit too short for my taste. `rustfmt --config-help` will give you a lot of options.

**Comment by GGist** [comment]
Ok thanks, i'll check that out.

**Pull request merged**
