### PR TITLE
support for listening on any interface

### PR DESCRIPTION
**Pull request by icorderi**
Some deployments require us to be able able continue listening even when the interfaces available change underneath us. 

To do so, we must _join a multicast group_ on **any** interface.

### CODE REVIEW

**Comment by icorderi** [comment]
@GGist 

As of right now, 
- the code works on **Linux**, should work on the **bsd's**
- I have verified it fails on **macOS** and, 
- I'm uncertain about **Windows**.

I'm still not sure about keeping:

```rust
#[cfg(not(linux))]
fn listen_any_on_port(port: u16) -> SSDPResult<SSDPReceiver<Self::Message>> {
    Self::listen_on_port(port)
}
```

Having it fallback to listening on interfaces that are present at that moment is a bit _misleading_.

---------------

It would be nice to figure out why **macOS** is rejecting interface `0`.
If you can verify it works on **Windows** we can change the code to be flagged as `#[cfg(not(macos))]` until we figure out how to make it work on it. 

---------------

> The first couple commits are on PR #36

**Comment by GGist** [comment]
@icorderi I agree that it is a bit confusing, though I do agree that this functionality is valuable.

I can confirm on Windows that joining with interface 0 will not work as intended as Windows will just [join on the default interface](https://msdn.microsoft.com/en-us/library/windows/desktop/ms738655(v=vs.85).aspx) if passed 0. The last time interface 0 came up in a previous PR I could not find out any way to achieve Linux like behavior for interface 0 on Windows.

The code looks good. Go ahead and remove this bit:
```
// Is is possible that binding on interface 0 works on the ipv6 stack in windows
// I have not tested it
```
And I'll merge it in.

Thanks!

**Comment by GGist** [comment]
On second thought, I think we should go ahead and just remove ```listen_any_on_port``` for non Linux platforms.

**Comment by icorderi** [comment]
@GGist, removed the _non-linux_ platform bits

**Comment by GGist** [comment]
Thanks!

**Pull request merged**
